## Imports

In [1]:
%load_ext autoreload
%autoreload 2

In [ ]:
import pandas as pd
import numpy as np
from os import walk

from sklearn.preprocessing import MinMaxScaler, RobustScaler
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    mean_absolute_percentage_error
)

pd.set_option('display.max_columns', None)

from src.get_tables import tickers
from src.model_functions import build_lstm_sequences, split_temporal, generate_lstm_model, get_study_optuna

## Funções

In [3]:
save_folder_path_refined = 'dados/refined'

features = [
    'close', 'high', 'low', 'open', 'volume',
    'close_dolar', 'close_ibovespa', 'close_sp_500', 'selic', 'ipca',
    'ma20', 'ma50', 'bb_upper', 'bb_lower', 'rsi_wilder', 'macd',
    'macd_signal', 'weekday_sin', 'weekday_cos', 'month_sin', 'month_cos'
]

In [38]:
tickers

['RENT3', 'LREN3', 'SMFT3', 'MULT3', 'VBBR3', 'ABEV3']

In [ ]:
for t in tickers:

    tabela_hiperparams = pd.DataFrame()

    df = pd.read_parquet(f"{save_folder_path_refined}/tb_analitica_{t}.parquet", engine = 'pyarrow')
    df = df[df['close'].notna()]
    df = df.sort_values("date").reset_index(drop=True)

    data = df[features].copy()

    # Divisão temporal ANTES do scaler (evita data leakage)
    n = len(data)
    train_end = int(n * 0.70)
    valid_end = int(n * 0.85)

    train_df = data.iloc[:train_end]
    valid_df = data.iloc[train_end:valid_end]
    test_df = data.iloc[valid_end:]

    scaler = MinMaxScaler()
    scaler.fit(train_df)

    scaled_data = np.vstack([
        scaler.transform(train_df),
        scaler.transform(valid_df),
        scaler.transform(test_df)
    ])

    for w in [60, 90, 120, 180]:
        print("=" * 60)
        print(f"Início dos estudos | Ticker = {t} | window_size = {w}")
        print("=" * 60)

        study = get_study_optuna(w, scaled_data, n_trials = 20, ticker = t)

        tmp = pd.DataFrame(data = {
            'ticker':[t],
            'window_size':[w],
            'val_loss':[study.best_value]

        })

        for k, v in study.best_params.items():
            tmp[k] = [v]

        tabela_hiperparams = pd.concat([tabela_hiperparams, tmp])
        print("\n\n")

    tabela_hiperparams.to_excel(f'dados/aux_data/tabela_hiperparametros_{t}.xlsx', index = False)

[I 2026-07-06 19:57:56,647] A new study created in memory with name: LSTM Stock Prediction | window_size = 60

============================================================
Início dos estudos | Ticker = SMFT3 | window_size = 60
============================================================
(1157, 60, 21)
(1157,)
Treino     : (809, 60, 21)
Validação  : (174, 60, 21)
Teste      : (174, 60, 21)

  0%|          | 0/20 [00:00<?, ?it/s]

g:\Meu Drive\5. Cursos\Pós ML Engineering\Fase 4 - Deep Learning e IA\lstm-stock-predictor-api\.venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

[I 2026-07-06 19:59:31,693] Trial 0 finished with value: 0.11379677057266235 and parameters: {'units_1': 64, 'units_2': 16, 'dropout': 0.3103085127176983, 'learning_rate': 0.0001245083489731155, 'batch_size': 32}. Best is trial 0 with value: 0.11379677057266235.
[I 2026-07-06 20:00:51,498] Trial 1 finished with value: 0.13822369277477264 and parameters: {'units_1': 64, 'units_2': 64, 'dropout': 0.3576303723549862, 'learning_rate': 0.00021057317087910492, 'batch_size': 64}. Best is trial 0 with value: 0.11379677057266235.
[I 2026-07-06 20:01:40,659] Trial 2 finished with value: 0.03645322844386101 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.24466685667763072, 'learning_rate': 0.005006273985645114, 'batch_size': 32}. Best is trial 2 with value: 0.03645322844386101.
[I 2026-07-06 20:03:29,334] Trial 3 finished with value: 0.03746684640645981 and parameters: {'units_1': 32, 'units_2': 16, 'dropout': 0.34980915033745785, 'learning_rate': 0.0006641720247204887, 'batch_size': 16}. Best is trial 2 with value: 0.03645322844386101.
[I 2026-07-06 20:04:58,803] Trial 4 finished with value: 0.20335383713245392 and parameters: {'units_1': 64, 'units_2': 16, 'dropout': 0.30783996222352117, 'learning_rate': 0.00012581965044677017, 'batch_size': 64}. Best is trial 2 with value: 0.03645322844386101.
[I 2026-07-06 20:06:29,180] Trial 5 finished with value: 0.037701454013586044 and parameters: {'units_1': 128, 'units_2': 16, 'dropout': 0.3902733470480536, 'learning_rate': 0.004691429064873818, 'batch_size': 64}. Best is trial 2 with value: 0.03645322844386101.
[I 2026-07-06 20:09:09,641] Trial 6 finished with value: 0.037864651530981064 and parameters: {'units_1': 64, 'units_2': 48, 'dropout': 0.4742155564321402, 'learning_rate': 0.0005243187244635072, 'batch_size': 32}. Best is trial 2 with value: 0.03645322844386101.
[I 2026-07-06 20:13:35,736] Trial 7 finished with value: 0.13552531599998474 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.2399797781145413, 'learning_rate': 0.00010539626651467382, 'batch_size': 32}. Best is trial 2 with value: 0.03645322844386101.
[I 2026-07-06 20:15:57,657] Trial 8 finished with value: 0.037547554820775986 and parameters: {'units_1': 128, 'units_2': 48, 'dropout': 0.27204587835065563, 'learning_rate': 0.0012063557352883884, 'batch_size': 16}. Best is trial 2 with value: 0.03645322844386101.
[I 2026-07-06 20:18:55,951] Trial 9 finished with value: 0.09846766293048859 and parameters: {'units_1': 128, 'units_2': 16, 'dropout': 0.35200497094002814, 'learning_rate': 0.0001406014816207837, 'batch_size': 32}. Best is trial 2 with value: 0.03645322844386101.
[I 2026-07-06 20:19:09,930] Trial 10 finished with value: 0.03676290065050125 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.116727550576742, 'learning_rate': 0.009511455316302151, 'batch_size': 32}. Best is trial 2 with value: 0.03645322844386101.
[I 2026-07-06 20:19:36,360] Trial 11 finished with value: 0.03601503744721413 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.12643407683227992, 'learning_rate': 0.009196586692092027, 'batch_size': 32}. Best is trial 11 with value: 0.03601503744721413.
[I 2026-07-06 20:20:03,823] Trial 12 finished with value: 0.037434302270412445 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.14795974182649987, 'learning_rate': 0.003729465958283556, 'batch_size': 32}. Best is trial 11 with value: 0.03601503744721413.
[I 2026-07-06 20:20:48,155] Trial 13 finished with value: 0.036132778972387314 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.19111309617463076, 'learning_rate': 0.006446186285347054, 'batch_size': 32}. Best is trial 11 with value: 0.03601503744721413.
[I 2026-07-06 20:21:05,036] Trial 14 finished with value: 0.0370209664106369 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.17942974651521648, 'learning_rate': 0.009577281438096516, 'batch_size': 32}. Best is trial 11 with value: 0.03601503744721413.
[I 2026-07-06 20:21:58,692] Trial 15 finished with value: 0.0370672233402729 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.18354746573477865, 'learning_rate': 0.0023041816374343264, 'batch_size': 16}. Best is trial 11 with value: 0.03601503744721413.
[I 2026-07-06 20:22:39,336] Trial 16 finished with value: 0.03710928186774254 and parameters: {'units_1': 32, 'units_2': 32, 'dropout': 0.11962824305126932, 'learning_rate': 0.0023567418520055697, 'batch_size': 32}. Best is trial 11 with value: 0.03601503744721413.
[I 2026-07-06 20:23:13,037] Trial 17 finished with value: 0.03702997788786888 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.1964862872825865, 'learning_rate': 0.006346297375172439, 'batch_size': 32}. Best is trial 11 with value: 0.03601503744721413.
[I 2026-07-06 20:23:47,011] Trial 18 finished with value: 0.03775626793503761 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.21326315407868893, 'learning_rate': 0.00287600906067355, 'batch_size': 64}. Best is trial 11 with value: 0.03601503744721413.

[I 2026-07-06 20:24:46,756] A new study created in memory with name: LSTM Stock Prediction | window_size = 90

[I 2026-07-06 20:24:46,737] Trial 19 finished with value: 0.03761341795325279 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.15706944706045756, 'learning_rate': 0.0013538206728763813, 'batch_size': 16}. Best is trial 11 with value: 0.03601503744721413.
============================================================
Melhores hiperparâmetros | Ticker = SMFT3 | window_size = 60
============================================================
units_1: 96
units_2: 32
dropout: 0.12643407683227992
learning_rate: 0.009196586692092027
batch_size: 32

Melhor validation loss:
0.03601503744721413



============================================================
Início dos estudos | Ticker = SMFT3 | window_size = 90
============================================================
(1127, 90, 21)
(1127,)
Treino     : (788, 90, 21)
Validação  : (169, 90, 21)
Teste      : (170, 90, 21)

  0%|          | 0/20 [00:00<?, ?it/s]

g:\Meu Drive\5. Cursos\Pós ML Engineering\Fase 4 - Deep Learning e IA\lstm-stock-predictor-api\.venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

[I 2026-07-06 20:25:48,600] Trial 0 finished with value: 0.04350120574235916 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.29308437853105684, 'learning_rate': 0.0029746858384148912, 'batch_size': 32}. Best is trial 0 with value: 0.04350120574235916.
[I 2026-07-06 20:27:49,763] Trial 1 finished with value: 0.04388529434800148 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.1491183910849633, 'learning_rate': 0.0006567626016931327, 'batch_size': 16}. Best is trial 0 with value: 0.04350120574235916.
[I 2026-07-06 20:28:50,489] Trial 2 finished with value: 0.043154049664735794 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.3892494498130873, 'learning_rate': 0.003005190216557448, 'batch_size': 64}. Best is trial 2 with value: 0.043154049664735794.
[I 2026-07-06 20:30:09,695] Trial 3 finished with value: 0.043731689453125 and parameters: {'units_1': 32, 'units_2': 16, 'dropout': 0.48711360489363176, 'learning_rate': 0.0012838047161510264, 'batch_size': 32}. Best is trial 2 with value: 0.043154049664735794.
[I 2026-07-06 20:31:43,088] Trial 4 finished with value: 0.04377323389053345 and parameters: {'units_1': 64, 'units_2': 16, 'dropout': 0.17490418340033997, 'learning_rate': 0.0008433945303370701, 'batch_size': 16}. Best is trial 2 with value: 0.043154049664735794.
[I 2026-07-06 20:32:55,124] Trial 5 finished with value: 0.054881248623132706 and parameters: {'units_1': 32, 'units_2': 32, 'dropout': 0.10208928998939806, 'learning_rate': 0.0005335908676894416, 'batch_size': 64}. Best is trial 2 with value: 0.043154049664735794.
[I 2026-07-06 20:34:09,315] Trial 6 finished with value: 0.19081781804561615 and parameters: {'units_1': 32, 'units_2': 32, 'dropout': 0.3697009852433638, 'learning_rate': 0.00015387174245577782, 'batch_size': 64}. Best is trial 2 with value: 0.043154049664735794.
[I 2026-07-06 20:35:28,919] Trial 7 finished with value: 0.043181683868169785 and parameters: {'units_1': 32, 'units_2': 32, 'dropout': 0.4333403580161672, 'learning_rate': 0.001125159906888813, 'batch_size': 16}. Best is trial 2 with value: 0.043154049664735794.
[I 2026-07-06 20:37:17,941] Trial 8 finished with value: 0.043659284710884094 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.29605712396168393, 'learning_rate': 0.001026678485919205, 'batch_size': 32}. Best is trial 2 with value: 0.043154049664735794.
[I 2026-07-06 20:38:04,202] Trial 9 finished with value: 0.043894995003938675 and parameters: {'units_1': 64, 'units_2': 48, 'dropout': 0.17918883744632477, 'learning_rate': 0.002608172946814161, 'batch_size': 32}. Best is trial 2 with value: 0.043154049664735794.
[I 2026-07-06 20:38:31,357] Trial 10 finished with value: 0.04219887778162956 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.271338649095814, 'learning_rate': 0.00970531246876027, 'batch_size': 64}. Best is trial 10 with value: 0.04219887778162956.
[I 2026-07-06 20:38:56,878] Trial 11 finished with value: 0.043000321835279465 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.3178972344118881, 'learning_rate': 0.009208920799150054, 'batch_size': 64}. Best is trial 10 with value: 0.04219887778162956.
[I 2026-07-06 20:39:23,634] Trial 12 finished with value: 0.04243085905909538 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.28554357096634614, 'learning_rate': 0.009962956137150357, 'batch_size': 64}. Best is trial 10 with value: 0.04219887778162956.
[I 2026-07-06 20:39:45,405] Trial 13 finished with value: 0.042895469814538956 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.23899845302654116, 'learning_rate': 0.009472968563267887, 'batch_size': 64}. Best is trial 10 with value: 0.04219887778162956.
[I 2026-07-06 20:40:28,721] Trial 14 finished with value: 0.04339488968253136 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.24831044286958298, 'learning_rate': 0.005142349407309938, 'batch_size': 64}. Best is trial 10 with value: 0.04219887778162956.
[I 2026-07-06 20:41:26,413] Trial 15 finished with value: 0.043235283344984055 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.24900509633135545, 'learning_rate': 0.005856890088162732, 'batch_size': 64}. Best is trial 10 with value: 0.04219887778162956.
[I 2026-07-06 20:42:04,288] Trial 16 finished with value: 0.043726757168769836 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.34487714094240024, 'learning_rate': 0.005058050027210004, 'batch_size': 64}. Best is trial 10 with value: 0.04219887778162956.
[I 2026-07-06 20:42:30,649] Trial 17 finished with value: 0.04120418801903725 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.21531772073870614, 'learning_rate': 0.00975551584295718, 'batch_size': 64}. Best is trial 17 with value: 0.04120418801903725.
[I 2026-07-06 20:44:00,157] Trial 18 finished with value: 0.043898191303014755 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.211358611245083, 'learning_rate': 0.00210881319982942, 'batch_size': 64}. Best is trial 17 with value: 0.04120418801903725.

[I 2026-07-06 20:45:16,129] A new study created in memory with name: LSTM Stock Prediction | window_size = 120

[I 2026-07-06 20:45:16,113] Trial 19 finished with value: 0.039574235677719116 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.1222218633277293, 'learning_rate': 0.00535648719999691, 'batch_size': 16}. Best is trial 19 with value: 0.039574235677719116.
============================================================
Melhores hiperparâmetros | Ticker = SMFT3 | window_size = 90
============================================================
units_1: 96
units_2: 48
dropout: 0.1222218633277293
learning_rate: 0.00535648719999691
batch_size: 16

Melhor validation loss:
0.039574235677719116



============================================================
Início dos estudos | Ticker = SMFT3 | window_size = 120
============================================================
(1097, 120, 21)
(1097,)
Treino     : (767, 120, 21)
Validação  : (165, 120, 21)
Teste      : (165, 120, 21)

  0%|          | 0/20 [00:00<?, ?it/s]

g:\Meu Drive\5. Cursos\Pós ML Engineering\Fase 4 - Deep Learning e IA\lstm-stock-predictor-api\.venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

[I 2026-07-06 20:47:40,411] Trial 0 finished with value: 0.04906192049384117 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.4446444999010878, 'learning_rate': 0.0009144707465077081, 'batch_size': 64}. Best is trial 0 with value: 0.04906192049384117.
[I 2026-07-06 20:51:16,033] Trial 1 finished with value: 0.1737731546163559 and parameters: {'units_1': 128, 'units_2': 32, 'dropout': 0.4418477758757958, 'learning_rate': 0.00010154777656585361, 'batch_size': 32}. Best is trial 0 with value: 0.04906192049384117.
[I 2026-07-06 20:52:40,040] Trial 2 finished with value: 0.047821901738643646 and parameters: {'units_1': 128, 'units_2': 16, 'dropout': 0.2741995481344641, 'learning_rate': 0.0019697278567741266, 'batch_size': 32}. Best is trial 2 with value: 0.047821901738643646.
[I 2026-07-06 20:54:03,703] Trial 3 finished with value: 0.04821472615003586 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.30139748008199285, 'learning_rate': 0.0018029974385952393, 'batch_size': 64}. Best is trial 2 with value: 0.047821901738643646.
[I 2026-07-06 20:55:23,019] Trial 4 finished with value: 0.04790957644581795 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.10248484145882797, 'learning_rate': 0.0029784452785023, 'batch_size': 32}. Best is trial 2 with value: 0.047821901738643646.
[I 2026-07-06 20:57:16,821] Trial 5 finished with value: 0.15229733288288116 and parameters: {'units_1': 64, 'units_2': 48, 'dropout': 0.18890353428083598, 'learning_rate': 0.00024032590996350006, 'batch_size': 64}. Best is trial 2 with value: 0.047821901738643646.
[I 2026-07-06 20:59:31,754] Trial 6 finished with value: 0.15346990525722504 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.38846685263913283, 'learning_rate': 0.00023868895135609246, 'batch_size': 64}. Best is trial 2 with value: 0.047821901738643646.
[I 2026-07-06 21:01:25,492] Trial 7 finished with value: 0.08973511308431625 and parameters: {'units_1': 64, 'units_2': 48, 'dropout': 0.44281594176280936, 'learning_rate': 0.0003941954401169418, 'batch_size': 64}. Best is trial 2 with value: 0.047821901738643646.
[I 2026-07-06 21:02:15,137] Trial 8 finished with value: 0.046751029789447784 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.296042556641574, 'learning_rate': 0.006806721972093629, 'batch_size': 32}. Best is trial 8 with value: 0.046751029789447784.
[I 2026-07-06 21:04:08,051] Trial 9 finished with value: 0.24474066495895386 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.3027346585389381, 'learning_rate': 0.00011985222251012238, 'batch_size': 64}. Best is trial 8 with value: 0.046751029789447784.
[I 2026-07-06 21:04:57,195] Trial 10 finished with value: 0.04518706351518631 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.18915556048130272, 'learning_rate': 0.006923826566665848, 'batch_size': 16}. Best is trial 10 with value: 0.04518706351518631.
[I 2026-07-06 21:06:35,749] Trial 11 finished with value: 0.04058944433927536 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.2085606577894792, 'learning_rate': 0.009867922907630422, 'batch_size': 16}. Best is trial 11 with value: 0.04058944433927536.
[I 2026-07-06 21:08:07,454] Trial 12 finished with value: 0.04607614502310753 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.1802960696937217, 'learning_rate': 0.009574823018941275, 'batch_size': 16}. Best is trial 11 with value: 0.04058944433927536.
[I 2026-07-06 21:09:29,444] Trial 13 finished with value: 0.04759057238698006 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.20204642084315205, 'learning_rate': 0.004543376760790181, 'batch_size': 16}. Best is trial 11 with value: 0.04058944433927536.
[I 2026-07-06 21:11:00,001] Trial 14 finished with value: 0.04669863358139992 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.1355248036290159, 'learning_rate': 0.005655592120618809, 'batch_size': 16}. Best is trial 11 with value: 0.04058944433927536.
[I 2026-07-06 21:13:44,161] Trial 15 finished with value: 0.03992234915494919 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.23699356625911777, 'learning_rate': 0.008717235670952363, 'batch_size': 16}. Best is trial 15 with value: 0.03992234915494919.
[I 2026-07-06 21:15:13,983] Trial 16 finished with value: 0.047639913856983185 and parameters: {'units_1': 32, 'units_2': 48, 'dropout': 0.24709010650642405, 'learning_rate': 0.0035813969085970185, 'batch_size': 16}. Best is trial 15 with value: 0.03992234915494919.
[I 2026-07-06 21:18:03,545] Trial 17 finished with value: 0.04484683647751808 and parameters: {'units_1': 64, 'units_2': 64, 'dropout': 0.3635747998832207, 'learning_rate': 0.008958200969621624, 'batch_size': 16}. Best is trial 15 with value: 0.03992234915494919.
[I 2026-07-06 21:20:33,484] Trial 18 finished with value: 0.046569354832172394 and parameters: {'units_1': 32, 'units_2': 48, 'dropout': 0.23967119269628184, 'learning_rate': 0.002822524334438806, 'batch_size': 16}. Best is trial 15 with value: 0.03992234915494919.

[I 2026-07-06 21:23:44,507] A new study created in memory with name: LSTM Stock Prediction | window_size = 180

[I 2026-07-06 21:23:44,484] Trial 19 finished with value: 0.04784238710999489 and parameters: {'units_1': 64, 'units_2': 64, 'dropout': 0.34495951603846625, 'learning_rate': 0.0012439081707342166, 'batch_size': 16}. Best is trial 15 with value: 0.03992234915494919.
============================================================
Melhores hiperparâmetros | Ticker = SMFT3 | window_size = 120
============================================================
units_1: 32
units_2: 64
dropout: 0.23699356625911777
learning_rate: 0.008717235670952363
batch_size: 16

Melhor validation loss:
0.03992234915494919



============================================================
Início dos estudos | Ticker = SMFT3 | window_size = 180
============================================================
(1037, 180, 21)
(1037,)
Treino     : (725, 180, 21)
Validação  : (156, 180, 21)
Teste      : (156, 180, 21)

  0%|          | 0/20 [00:00<?, ?it/s]

g:\Meu Drive\5. Cursos\Pós ML Engineering\Fase 4 - Deep Learning e IA\lstm-stock-predictor-api\.venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

[I 2026-07-06 21:28:13,619] Trial 0 finished with value: 0.054997436702251434 and parameters: {'units_1': 32, 'units_2': 48, 'dropout': 0.2682908431275493, 'learning_rate': 0.0008322364879420759, 'batch_size': 32}. Best is trial 0 with value: 0.054997436702251434.
[I 2026-07-06 21:31:41,509] Trial 1 finished with value: 0.054948825389146805 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.10716009205062514, 'learning_rate': 0.0011704628096170426, 'batch_size': 32}. Best is trial 1 with value: 0.054948825389146805.
[I 2026-07-06 21:33:22,844] Trial 2 finished with value: 0.052618321031332016 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.3662114280573189, 'learning_rate': 0.005646074252788164, 'batch_size': 16}. Best is trial 2 with value: 0.052618321031332016.
[I 2026-07-06 21:38:44,203] Trial 3 finished with value: 0.054848916828632355 and parameters: {'units_1': 128, 'units_2': 16, 'dropout': 0.4156445628191049, 'learning_rate': 0.0014935379681420148, 'batch_size': 64}. Best is trial 2 with value: 0.052618321031332016.
[I 2026-07-06 21:40:31,342] Trial 4 finished with value: 0.054349686950445175 and parameters: {'units_1': 32, 'units_2': 48, 'dropout': 0.1251724713821299, 'learning_rate': 0.0028134874253793974, 'batch_size': 16}. Best is trial 2 with value: 0.052618321031332016.
[I 2026-07-06 21:43:49,985] Trial 5 finished with value: 0.20002654194831848 and parameters: {'units_1': 64, 'units_2': 48, 'dropout': 0.48608904219539506, 'learning_rate': 0.00019934900847948665, 'batch_size': 64}. Best is trial 2 with value: 0.052618321031332016.
[I 2026-07-06 21:50:00,136] Trial 6 finished with value: 0.060108669102191925 and parameters: {'units_1': 128, 'units_2': 48, 'dropout': 0.4521339426036237, 'learning_rate': 0.0007160435969074617, 'batch_size': 64}. Best is trial 2 with value: 0.052618321031332016.
[I 2026-07-06 21:53:10,958] Trial 7 finished with value: 0.057201310992240906 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.39973022270456704, 'learning_rate': 0.0008293851172514687, 'batch_size': 64}. Best is trial 2 with value: 0.052618321031332016.
[I 2026-07-06 21:55:13,860] Trial 8 finished with value: 0.054639481008052826 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.4348656085229293, 'learning_rate': 0.002094433733038981, 'batch_size': 64}. Best is trial 2 with value: 0.052618321031332016.
[I 2026-07-06 21:58:33,437] Trial 9 finished with value: 0.05415311083197594 and parameters: {'units_1': 64, 'units_2': 64, 'dropout': 0.29622121954000324, 'learning_rate': 0.0016566736937336742, 'batch_size': 64}. Best is trial 2 with value: 0.052618321031332016.
[I 2026-07-06 22:02:10,589] Trial 10 finished with value: 0.046978872269392014 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.24033328515526353, 'learning_rate': 0.009913642654457041, 'batch_size': 16}. Best is trial 10 with value: 0.046978872269392014.
[I 2026-07-06 22:03:59,663] Trial 11 finished with value: 0.04948778077960014 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.2841872691227528, 'learning_rate': 0.009013938908960515, 'batch_size': 16}. Best is trial 10 with value: 0.046978872269392014.
[I 2026-07-06 22:05:52,278] Trial 12 finished with value: 0.04997354373335838 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.21913828690738948, 'learning_rate': 0.008984547386153204, 'batch_size': 16}. Best is trial 10 with value: 0.046978872269392014.
[I 2026-07-06 22:07:43,902] Trial 13 finished with value: 0.05041620135307312 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.18570678565227222, 'learning_rate': 0.00862257184266939, 'batch_size': 16}. Best is trial 10 with value: 0.046978872269392014.
[I 2026-07-06 22:09:52,579] Trial 14 finished with value: 0.05380609259009361 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.323343674838101, 'learning_rate': 0.004196360494774602, 'batch_size': 16}. Best is trial 10 with value: 0.046978872269392014.
[I 2026-07-06 22:14:26,685] Trial 15 finished with value: 0.0490134172141552 and parameters: {'units_1': 128, 'units_2': 16, 'dropout': 0.22117921969180093, 'learning_rate': 0.004689756238578609, 'batch_size': 16}. Best is trial 10 with value: 0.046978872269392014.
[I 2026-07-06 22:17:38,158] Trial 16 finished with value: 0.053228750824928284 and parameters: {'units_1': 128, 'units_2': 32, 'dropout': 0.22232728171295113, 'learning_rate': 0.004140334684175118, 'batch_size': 16}. Best is trial 10 with value: 0.046978872269392014.
[I 2026-07-06 22:26:30,270] Trial 17 finished with value: 0.05496761575341225 and parameters: {'units_1': 128, 'units_2': 16, 'dropout': 0.17754373069555324, 'learning_rate': 0.0002972927521720373, 'batch_size': 16}. Best is trial 10 with value: 0.046978872269392014.
[I 2026-07-06 22:28:04,028] Trial 18 finished with value: 0.05440221726894379 and parameters: {'units_1': 128, 'units_2': 16, 'dropout': 0.2315888406642779, 'learning_rate': 0.005250232569376051, 'batch_size': 32}. Best is trial 10 with value: 0.046978872269392014.

[I 2026-07-06 22:31:06,485] A new study created in memory with name: LSTM Stock Prediction | window_size = 60

[I 2026-07-06 22:31:06,410] Trial 19 finished with value: 0.053999774158000946 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.15771918777494326, 'learning_rate': 0.0026759611414226103, 'batch_size': 16}. Best is trial 10 with value: 0.046978872269392014.
============================================================
Melhores hiperparâmetros | Ticker = SMFT3 | window_size = 180
============================================================
units_1: 96
units_2: 16
dropout: 0.24033328515526353
learning_rate: 0.009913642654457041
batch_size: 16

Melhor validation loss:
0.046978872269392014



============================================================
Início dos estudos | Ticker = MULT3 | window_size = 60
============================================================
(2409, 60, 21)
(2409,)
Treino     : (1686, 60, 21)
Validação  : (361, 60, 21)
Teste      : (362, 60, 21)

  0%|          | 0/20 [00:00<?, ?it/s]

g:\Meu Drive\5. Cursos\Pós ML Engineering\Fase 4 - Deep Learning e IA\lstm-stock-predictor-api\.venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

[I 2026-07-06 22:32:59,638] Trial 0 finished with value: 0.04201875254511833 and parameters: {'units_1': 32, 'units_2': 48, 'dropout': 0.22592528578366433, 'learning_rate': 0.0015697594012911613, 'batch_size': 32}. Best is trial 0 with value: 0.04201875254511833.
[I 2026-07-06 22:34:58,064] Trial 1 finished with value: 0.042444486171007156 and parameters: {'units_1': 64, 'units_2': 16, 'dropout': 0.3339096909197634, 'learning_rate': 0.0007524396184027909, 'batch_size': 16}. Best is trial 0 with value: 0.04201875254511833.
[I 2026-07-06 22:36:15,233] Trial 2 finished with value: 0.03886053338646889 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.2604656786762062, 'learning_rate': 0.006613280186960351, 'batch_size': 32}. Best is trial 2 with value: 0.03886053338646889.
[I 2026-07-06 22:37:12,537] Trial 3 finished with value: 0.03652751445770264 and parameters: {'units_1': 32, 'units_2': 48, 'dropout': 0.3142794478959191, 'learning_rate': 0.009230357924143461, 'batch_size': 16}. Best is trial 3 with value: 0.03652751445770264.
[I 2026-07-06 22:42:34,062] Trial 4 finished with value: 0.042944375425577164 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.21311155531558326, 'learning_rate': 0.0002321785137123453, 'batch_size': 16}. Best is trial 3 with value: 0.03652751445770264.
[I 2026-07-06 22:44:35,414] Trial 5 finished with value: 0.04308687523007393 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.2835594810548462, 'learning_rate': 0.0005574382346116723, 'batch_size': 64}. Best is trial 3 with value: 0.03652751445770264.
[I 2026-07-06 22:45:36,123] Trial 6 finished with value: 0.040323156863451004 and parameters: {'units_1': 32, 'units_2': 16, 'dropout': 0.13438917078415052, 'learning_rate': 0.0030145296818425743, 'batch_size': 32}. Best is trial 3 with value: 0.03652751445770264.
[I 2026-07-06 22:47:09,094] Trial 7 finished with value: 0.042629025876522064 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.4267492076388012, 'learning_rate': 0.0013238075291273734, 'batch_size': 32}. Best is trial 3 with value: 0.03652751445770264.
[I 2026-07-06 22:48:23,752] Trial 8 finished with value: 0.04170193150639534 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.21051877565532562, 'learning_rate': 0.002138892163242721, 'batch_size': 32}. Best is trial 3 with value: 0.03652751445770264.
[I 2026-07-06 22:50:09,188] Trial 9 finished with value: 0.04113626107573509 and parameters: {'units_1': 128, 'units_2': 32, 'dropout': 0.23781607461922216, 'learning_rate': 0.0014983655951194576, 'batch_size': 16}. Best is trial 3 with value: 0.03652751445770264.
[I 2026-07-06 22:53:08,498] Trial 10 finished with value: 0.04911638796329498 and parameters: {'units_1': 64, 'units_2': 64, 'dropout': 0.4774573598778819, 'learning_rate': 0.0001463352752860419, 'batch_size': 64}. Best is trial 3 with value: 0.03652751445770264.
[I 2026-07-06 22:54:36,558] Trial 11 finished with value: 0.03469337895512581 and parameters: {'units_1': 128, 'units_2': 48, 'dropout': 0.35547074368633014, 'learning_rate': 0.009415194626014265, 'batch_size': 16}. Best is trial 11 with value: 0.03469337895512581.
[I 2026-07-06 22:57:20,999] Trial 12 finished with value: 0.03540636971592903 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.3588690785213945, 'learning_rate': 0.007705142566857655, 'batch_size': 16}. Best is trial 11 with value: 0.03469337895512581.
[I 2026-07-06 22:59:40,140] Trial 13 finished with value: 0.03945256024599075 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.3704813822348918, 'learning_rate': 0.004486419967829874, 'batch_size': 16}. Best is trial 11 with value: 0.03469337895512581.
[I 2026-07-06 23:00:44,983] Trial 14 finished with value: 0.03984362259507179 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.4107321867731081, 'learning_rate': 0.009884888268701734, 'batch_size': 16}. Best is trial 11 with value: 0.03469337895512581.
[I 2026-07-06 23:03:29,119] Trial 15 finished with value: 0.03851684555411339 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.3759989820885492, 'learning_rate': 0.004554267181428644, 'batch_size': 16}. Best is trial 11 with value: 0.03469337895512581.
[I 2026-07-06 23:04:04,964] Trial 16 finished with value: 0.04208788648247719 and parameters: {'units_1': 128, 'units_2': 32, 'dropout': 0.49807853738228236, 'learning_rate': 0.0048524491981422925, 'batch_size': 64}. Best is trial 11 with value: 0.03469337895512581.
[I 2026-07-06 23:05:20,621] Trial 17 finished with value: 0.04147161543369293 and parameters: {'units_1': 128, 'units_2': 48, 'dropout': 0.42962405529323106, 'learning_rate': 0.003147932039293271, 'batch_size': 16}. Best is trial 11 with value: 0.03469337895512581.
[I 2026-07-06 23:07:39,387] Trial 18 finished with value: 0.03813764825463295 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.35116040717556507, 'learning_rate': 0.007039702343000349, 'batch_size': 16}. Best is trial 11 with value: 0.03469337895512581.

[I 2026-07-06 23:10:17,803] A new study created in memory with name: LSTM Stock Prediction | window_size = 90

[I 2026-07-06 23:10:17,783] Trial 19 finished with value: 0.03938373178243637 and parameters: {'units_1': 64, 'units_2': 48, 'dropout': 0.30471289215096725, 'learning_rate': 0.003164132360882647, 'batch_size': 16}. Best is trial 11 with value: 0.03469337895512581.
============================================================
Melhores hiperparâmetros | Ticker = MULT3 | window_size = 60
============================================================
units_1: 128
units_2: 48
dropout: 0.35547074368633014
learning_rate: 0.009415194626014265
batch_size: 16

Melhor validation loss:
0.03469337895512581



============================================================
Início dos estudos | Ticker = MULT3 | window_size = 90
============================================================
(2379, 90, 21)
(2379,)
Treino     : (1665, 90, 21)
Validação  : (357, 90, 21)
Teste      : (357, 90, 21)

  0%|          | 0/20 [00:00<?, ?it/s]

g:\Meu Drive\5. Cursos\Pós ML Engineering\Fase 4 - Deep Learning e IA\lstm-stock-predictor-api\.venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

[I 2026-07-06 23:18:10,593] Trial 0 finished with value: 0.036970123648643494 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.4798285513197713, 'learning_rate': 0.0033931109924214206, 'batch_size': 16}. Best is trial 0 with value: 0.036970123648643494.
[I 2026-07-06 23:22:12,475] Trial 1 finished with value: 0.0377737320959568 and parameters: {'units_1': 64, 'units_2': 64, 'dropout': 0.11340311850925483, 'learning_rate': 0.0035071223715392548, 'batch_size': 16}. Best is trial 0 with value: 0.036970123648643494.
[I 2026-07-06 23:30:57,775] Trial 2 finished with value: 0.048842236399650574 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.33017597472269977, 'learning_rate': 0.00014191510479748644, 'batch_size': 64}. Best is trial 0 with value: 0.036970123648643494.
[I 2026-07-06 23:41:46,505] Trial 3 finished with value: 0.04047403112053871 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.2592169839724237, 'learning_rate': 0.00023057311954698923, 'batch_size': 16}. Best is trial 0 with value: 0.036970123648643494.
[I 2026-07-06 23:44:38,841] Trial 4 finished with value: 0.039949800819158554 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.41488332632622893, 'learning_rate': 0.0011798462491097686, 'batch_size': 32}. Best is trial 0 with value: 0.036970123648643494.
[I 2026-07-06 23:45:30,457] Trial 5 finished with value: 0.03940609097480774 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.17590399676659071, 'learning_rate': 0.004857546208411184, 'batch_size': 64}. Best is trial 0 with value: 0.036970123648643494.
[I 2026-07-06 23:52:06,063] Trial 6 finished with value: 0.041409045457839966 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.14532378918914649, 'learning_rate': 0.00015903132408601558, 'batch_size': 32}. Best is trial 0 with value: 0.036970123648643494.
[I 2026-07-06 23:57:04,644] Trial 7 finished with value: 0.03809843957424164 and parameters: {'units_1': 128, 'units_2': 32, 'dropout': 0.3431223706931611, 'learning_rate': 0.001870740601290645, 'batch_size': 16}. Best is trial 0 with value: 0.036970123648643494.
[I 2026-07-07 00:02:30,690] Trial 8 finished with value: 0.041679974645376205 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.4175463764346544, 'learning_rate': 0.0002224148483868644, 'batch_size': 64}. Best is trial 0 with value: 0.036970123648643494.
[I 2026-07-07 00:07:27,065] Trial 9 finished with value: 0.06383709609508514 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.42427540126990404, 'learning_rate': 0.0001002760931067978, 'batch_size': 64}. Best is trial 0 with value: 0.036970123648643494.
[I 2026-07-07 00:10:22,422] Trial 10 finished with value: 0.04036800190806389 and parameters: {'units_1': 64, 'units_2': 16, 'dropout': 0.4840602003821393, 'learning_rate': 0.0006023139815157136, 'batch_size': 16}. Best is trial 0 with value: 0.036970123648643494.
[I 2026-07-07 00:13:26,640] Trial 11 finished with value: 0.03155320882797241 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.10144240724940912, 'learning_rate': 0.00963655385737226, 'batch_size': 16}. Best is trial 11 with value: 0.03155320882797241.
[I 2026-07-07 00:16:55,305] Trial 12 finished with value: 0.03029380738735199 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.2291245132958113, 'learning_rate': 0.009341225088415676, 'batch_size': 16}. Best is trial 12 with value: 0.03029380738735199.
[I 2026-07-07 00:19:26,419] Trial 13 finished with value: 0.03269822895526886 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.21630433786986628, 'learning_rate': 0.00999447496058228, 'batch_size': 16}. Best is trial 12 with value: 0.03029380738735199.
[I 2026-07-07 00:20:55,928] Trial 14 finished with value: 0.03684898838400841 and parameters: {'units_1': 64, 'units_2': 48, 'dropout': 0.25157325020233423, 'learning_rate': 0.009000943691410771, 'batch_size': 16}. Best is trial 12 with value: 0.03029380738735199.
[I 2026-07-07 00:22:11,016] Trial 15 finished with value: 0.03784206509590149 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.10746339257992077, 'learning_rate': 0.005710590292002947, 'batch_size': 16}. Best is trial 12 with value: 0.03029380738735199.
[I 2026-07-07 00:24:07,817] Trial 16 finished with value: 0.03443426638841629 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.18152940567035697, 'learning_rate': 0.006202537852683536, 'batch_size': 32}. Best is trial 12 with value: 0.03029380738735199.
[I 2026-07-07 00:26:47,146] Trial 17 finished with value: 0.03778480738401413 and parameters: {'units_1': 32, 'units_2': 16, 'dropout': 0.27209317241648673, 'learning_rate': 0.0022232954208535106, 'batch_size': 16}. Best is trial 12 with value: 0.03029380738735199.
[I 2026-07-07 00:28:55,531] Trial 18 finished with value: 0.03668276220560074 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.3003101732111501, 'learning_rate': 0.00962280537783252, 'batch_size': 16}. Best is trial 12 with value: 0.03029380738735199.

[I 2026-07-07 00:30:43,445] A new study created in memory with name: LSTM Stock Prediction | window_size = 120

[I 2026-07-07 00:30:43,416] Trial 19 finished with value: 0.0388210266828537 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.21020071701678766, 'learning_rate': 0.0036075696867213305, 'batch_size': 32}. Best is trial 12 with value: 0.03029380738735199.
============================================================
Melhores hiperparâmetros | Ticker = MULT3 | window_size = 90
============================================================
units_1: 64
units_2: 32
dropout: 0.2291245132958113
learning_rate: 0.009341225088415676
batch_size: 16

Melhor validation loss:
0.03029380738735199



============================================================
Início dos estudos | Ticker = MULT3 | window_size = 120
============================================================
(2349, 120, 21)
(2349,)
Treino     : (1644, 120, 21)
Validação  : (352, 120, 21)
Teste      : (353, 120, 21)

  0%|          | 0/20 [00:00<?, ?it/s]

g:\Meu Drive\5. Cursos\Pós ML Engineering\Fase 4 - Deep Learning e IA\lstm-stock-predictor-api\.venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

[I 2026-07-07 00:36:45,636] Trial 0 finished with value: 0.03891879692673683 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.2268815614954333, 'learning_rate': 0.00034913002771639863, 'batch_size': 64}. Best is trial 0 with value: 0.03891879692673683.
[I 2026-07-07 00:38:01,000] Trial 1 finished with value: 0.03850026801228523 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.2444794490389598, 'learning_rate': 0.002623024289687597, 'batch_size': 64}. Best is trial 1 with value: 0.03850026801228523.
[I 2026-07-07 00:48:17,165] Trial 2 finished with value: 0.038814838975667953 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.4406585251753895, 'learning_rate': 0.00012047542513675955, 'batch_size': 16}. Best is trial 1 with value: 0.03850026801228523.
[I 2026-07-07 00:52:57,906] Trial 3 finished with value: 0.038867153227329254 and parameters: {'units_1': 32, 'units_2': 32, 'dropout': 0.4347214177832749, 'learning_rate': 0.00040126793584918565, 'batch_size': 64}. Best is trial 1 with value: 0.03850026801228523.
[I 2026-07-07 00:57:03,702] Trial 4 finished with value: 0.03876151517033577 and parameters: {'units_1': 128, 'units_2': 48, 'dropout': 0.16274817126770363, 'learning_rate': 0.0011467973162440374, 'batch_size': 64}. Best is trial 1 with value: 0.03850026801228523.
[I 2026-07-07 01:00:12,240] Trial 5 finished with value: 0.03876638785004616 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.20817172044450416, 'learning_rate': 0.0008770544196983093, 'batch_size': 32}. Best is trial 1 with value: 0.03850026801228523.
[I 2026-07-07 01:02:37,455] Trial 6 finished with value: 0.03632046654820442 and parameters: {'units_1': 32, 'units_2': 32, 'dropout': 0.1657511140294549, 'learning_rate': 0.0021268787278936377, 'batch_size': 16}. Best is trial 6 with value: 0.03632046654820442.
[I 2026-07-07 01:06:28,265] Trial 7 finished with value: 0.03870368003845215 and parameters: {'units_1': 64, 'units_2': 64, 'dropout': 0.12016182583405338, 'learning_rate': 0.001100771009378139, 'batch_size': 64}. Best is trial 6 with value: 0.03632046654820442.
[I 2026-07-07 01:10:32,663] Trial 8 finished with value: 0.03711031749844551 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.15497773795541292, 'learning_rate': 0.0019779024315426394, 'batch_size': 16}. Best is trial 6 with value: 0.03632046654820442.
[I 2026-07-07 01:14:54,099] Trial 9 finished with value: 0.0387941338121891 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.18127075120377426, 'learning_rate': 0.0004636540073887798, 'batch_size': 32}. Best is trial 6 with value: 0.03632046654820442.
[I 2026-07-07 01:20:44,131] Trial 10 finished with value: 0.03108394891023636 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.32561072093632826, 'learning_rate': 0.009791086462832974, 'batch_size': 16}. Best is trial 10 with value: 0.03108394891023636.
[I 2026-07-07 01:24:24,538] Trial 11 finished with value: 0.031922295689582825 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.33632984178461317, 'learning_rate': 0.007232049456971009, 'batch_size': 16}. Best is trial 10 with value: 0.03108394891023636.
[I 2026-07-07 01:26:26,912] Trial 12 finished with value: 0.03469931706786156 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.34041828153600523, 'learning_rate': 0.009919109710357234, 'batch_size': 16}. Best is trial 10 with value: 0.03108394891023636.
[I 2026-07-07 01:30:44,779] Trial 13 finished with value: 0.03133609518408775 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.3357655736943867, 'learning_rate': 0.00963605551999301, 'batch_size': 16}. Best is trial 10 with value: 0.03108394891023636.
[I 2026-07-07 01:33:43,219] Trial 14 finished with value: 0.03437456116080284 and parameters: {'units_1': 32, 'units_2': 48, 'dropout': 0.32872898525188243, 'learning_rate': 0.005082222187581491, 'batch_size': 16}. Best is trial 10 with value: 0.03108394891023636.
[I 2026-07-07 01:37:27,921] Trial 15 finished with value: 0.03374579921364784 and parameters: {'units_1': 32, 'units_2': 48, 'dropout': 0.2753447152005052, 'learning_rate': 0.0042117013659440095, 'batch_size': 16}. Best is trial 10 with value: 0.03108394891023636.
[I 2026-07-07 01:41:08,595] Trial 16 finished with value: 0.028324265033006668 and parameters: {'units_1': 64, 'units_2': 64, 'dropout': 0.30618407209730203, 'learning_rate': 0.008948811561232728, 'batch_size': 16}. Best is trial 16 with value: 0.028324265033006668.
[I 2026-07-07 01:43:52,125] Trial 17 finished with value: 0.036806974560022354 and parameters: {'units_1': 64, 'units_2': 48, 'dropout': 0.3756731450543812, 'learning_rate': 0.004643763361862104, 'batch_size': 32}. Best is trial 16 with value: 0.028324265033006668.
[I 2026-07-07 01:48:50,118] Trial 18 finished with value: 0.03474344313144684 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.2773455436460351, 'learning_rate': 0.0034419056257503277, 'batch_size': 16}. Best is trial 16 with value: 0.028324265033006668.

[I 2026-07-07 01:53:45,047] A new study created in memory with name: LSTM Stock Prediction | window_size = 180

[I 2026-07-07 01:53:45,029] Trial 19 finished with value: 0.034698061645030975 and parameters: {'units_1': 64, 'units_2': 64, 'dropout': 0.4940859939329632, 'learning_rate': 0.00644874684902896, 'batch_size': 16}. Best is trial 16 with value: 0.028324265033006668.
============================================================
Melhores hiperparâmetros | Ticker = MULT3 | window_size = 120
============================================================
units_1: 64
units_2: 64
dropout: 0.30618407209730203
learning_rate: 0.008948811561232728
batch_size: 16

Melhor validation loss:
0.028324265033006668



============================================================
Início dos estudos | Ticker = MULT3 | window_size = 180
============================================================
(2289, 180, 21)
(2289,)
Treino     : (1602, 180, 21)
Validação  : (343, 180, 21)
Teste      : (344, 180, 21)

  0%|          | 0/20 [00:00<?, ?it/s]

g:\Meu Drive\5. Cursos\Pós ML Engineering\Fase 4 - Deep Learning e IA\lstm-stock-predictor-api\.venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

[I 2026-07-07 02:08:02,171] Trial 0 finished with value: 0.041008077561855316 and parameters: {'units_1': 128, 'units_2': 48, 'dropout': 0.23059270964959588, 'learning_rate': 0.00016001166348372277, 'batch_size': 64}. Best is trial 0 with value: 0.041008077561855316.
[I 2026-07-07 02:13:04,447] Trial 1 finished with value: 0.033530402928590775 and parameters: {'units_1': 96, 'units_2': 64, 'dropout': 0.19245011108453355, 'learning_rate': 0.0037045648853674643, 'batch_size': 32}. Best is trial 1 with value: 0.033530402928590775.
[I 2026-07-07 02:27:45,468] Trial 2 finished with value: 0.04407649114727974 and parameters: {'units_1': 128, 'units_2': 48, 'dropout': 0.2894340915186312, 'learning_rate': 0.00014468607135246285, 'batch_size': 64}. Best is trial 1 with value: 0.033530402928590775.
[I 2026-07-07 02:31:04,676] Trial 3 finished with value: 0.034433480352163315 and parameters: {'units_1': 128, 'units_2': 32, 'dropout': 0.4936499725977531, 'learning_rate': 0.002503108111619978, 'batch_size': 32}. Best is trial 1 with value: 0.033530402928590775.
[I 2026-07-07 02:32:58,385] Trial 4 finished with value: 0.03365471214056015 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.3604595439123355, 'learning_rate': 0.003071835745755047, 'batch_size': 64}. Best is trial 1 with value: 0.033530402928590775.
[I 2026-07-07 02:38:51,716] Trial 5 finished with value: 0.03505338728427887 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.4064761726087308, 'learning_rate': 0.0005188132071175345, 'batch_size': 64}. Best is trial 1 with value: 0.033530402928590775.
[I 2026-07-07 02:47:28,833] Trial 6 finished with value: 0.03504348173737526 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.4419338812619157, 'learning_rate': 0.0003300360640396995, 'batch_size': 16}. Best is trial 1 with value: 0.033530402928590775.
[I 2026-07-07 02:54:53,677] Trial 7 finished with value: 0.03498575836420059 and parameters: {'units_1': 64, 'units_2': 64, 'dropout': 0.4589884379009317, 'learning_rate': 0.0005201939506244448, 'batch_size': 32}. Best is trial 1 with value: 0.033530402928590775.
[I 2026-07-07 03:04:51,017] Trial 8 finished with value: 0.034902140498161316 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.11105335264077035, 'learning_rate': 0.00022026976088959744, 'batch_size': 16}. Best is trial 1 with value: 0.033530402928590775.
[I 2026-07-07 03:15:50,749] Trial 9 finished with value: 0.03511537238955498 and parameters: {'units_1': 64, 'units_2': 16, 'dropout': 0.45251633221643905, 'learning_rate': 0.00015020465067036413, 'batch_size': 16}. Best is trial 1 with value: 0.033530402928590775.
[I 2026-07-07 03:18:18,397] Trial 10 finished with value: 0.03245773911476135 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.11227896237296742, 'learning_rate': 0.00935598243493764, 'batch_size': 32}. Best is trial 10 with value: 0.03245773911476135.
[I 2026-07-07 03:19:51,752] Trial 11 finished with value: 0.03166382387280464 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.11120288584046453, 'learning_rate': 0.009604326876055723, 'batch_size': 32}. Best is trial 11 with value: 0.03166382387280464.
[I 2026-07-07 03:21:24,306] Trial 12 finished with value: 0.03074885904788971 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.1028842104110818, 'learning_rate': 0.008782655622024007, 'batch_size': 32}. Best is trial 12 with value: 0.03074885904788971.
[I 2026-07-07 03:22:52,162] Trial 13 finished with value: 0.03064398653805256 and parameters: {'units_1': 32, 'units_2': 48, 'dropout': 0.16442691366733983, 'learning_rate': 0.009876254271654783, 'batch_size': 32}. Best is trial 13 with value: 0.03064398653805256.
[I 2026-07-07 03:25:37,310] Trial 14 finished with value: 0.03284512832760811 and parameters: {'units_1': 32, 'units_2': 48, 'dropout': 0.1850901256607872, 'learning_rate': 0.004929064139467951, 'batch_size': 32}. Best is trial 13 with value: 0.03064398653805256.
[I 2026-07-07 03:29:12,332] Trial 15 finished with value: 0.03457656502723694 and parameters: {'units_1': 32, 'units_2': 48, 'dropout': 0.16989396084214745, 'learning_rate': 0.001519267827118613, 'batch_size': 32}. Best is trial 13 with value: 0.03064398653805256.
[I 2026-07-07 03:33:06,502] Trial 16 finished with value: 0.03187089413404465 and parameters: {'units_1': 32, 'units_2': 48, 'dropout': 0.2725457982666633, 'learning_rate': 0.005701942736030524, 'batch_size': 32}. Best is trial 13 with value: 0.03064398653805256.
[I 2026-07-07 03:39:06,887] Trial 17 finished with value: 0.03474970534443855 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.15224790965350327, 'learning_rate': 0.0016771620494508489, 'batch_size': 32}. Best is trial 13 with value: 0.03064398653805256.
[I 2026-07-07 03:43:06,456] Trial 18 finished with value: 0.03201315179467201 and parameters: {'units_1': 64, 'units_2': 16, 'dropout': 0.2191504436901926, 'learning_rate': 0.006832727416428088, 'batch_size': 32}. Best is trial 13 with value: 0.03064398653805256.
[I 2026-07-07 03:51:40,415] Trial 19 finished with value: 0.03304055333137512 and parameters: {'units_1': 32, 'units_2': 48, 'dropout': 0.283856745212752, 'learning_rate': 0.0016023233176237898, 'batch_size': 16}. Best is trial 13 with value: 0.03064398653805256.
============================================================
Melhores hiperparâmetros | Ticker = MULT3 | window_size = 180
============================================================
units_1: 32
units_2: 48
dropout: 0.16442691366733983
learning_rate: 0.009876254271654783
batch_size: 32

Melhor validation loss:
0.03064398653805256

OSError: [WinError 433] Foi especificado um dispositivo inexistente: 'dados\\aux_data'

In [6]:
tabela_hiperparams

,ticker,window_size,val_loss,units_1,units_2,dropout,learning_rate,batch_size
0,RENT3,60,0.06,96,16,0.10,0.01,32
0,RENT3,90,0.05,96,48,0.41,0.00,64
0,RENT3,120,0.03,96,48,0.20,0.01,16
0,RENT3,180,0.03,32,32,0.21,0.01,16
0,LREN3,60,0.00,64,16,0.50,0.00,16
0,LREN3,90,0.00,32,48,0.25,0.00,32
0,LREN3,120,0.00,32,32,0.17,0.00,64
0,LREN3,180,0.00,32,48,0.44,0.00,64

In [30]:
tabela_hiperparams

,ticker,window_size,val_loss,units_1,units_2,dropout,learning_rate,batch_size
0,MULT3,60,0.03,128,48,0.36,0.01,16
0,MULT3,90,0.03,64,32,0.23,0.01,16
0,MULT3,120,0.03,64,64,0.31,0.01,16
0,MULT3,180,0.03,32,48,0.16,0.01,32

In [39]:
# tabela_hiperparams.to_excel(r'C:\Users\Hydra\Downloads\tabela_hiperparametros_MULT3.xlsx', index = False)

In [6]:
tabela_hiperparams = pd.DataFrame()

df = pd.read_parquet(f"{save_folder_path_refined}/tb_analitica_VBBR3.parquet", engine = 'pyarrow')
df = df[df['close'].notna()]
df = df.sort_values("date").reset_index(drop=True)

data = df[features].copy()

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

for w in [60, 90, 120, 180]:
    print("=" * 60)
    print(f"Início dos estudos | Ticker = VBBR3 | window_size = {w}")
    print("=" * 60)

    study = get_study_optuna(w, scaled_data, n_trials = 20, ticker = 'VBBR3')

    tmp = pd.DataFrame(data = {
        'ticker':['VBBR3'],
        'window_size':[w],
        'val_loss':[study.best_value]

    })

    for k, v in study.best_params.items():
        tmp[k] = [v]

    tabela_hiperparams = pd.concat([tabela_hiperparams, tmp])
    print("\n\n")

tabela_hiperparams.to_excel(r'C:\Users\Hydra\Downloads\tabela_hiperparametros_VBBR3.xlsx', index = False)

[I 2026-07-07 07:05:54,671] A new study created in memory with name: LSTM Stock Prediction | window_size = 60

============================================================
Início dos estudos | Ticker = VBBR3 | window_size = 60
============================================================
(1980, 60, 21)
(1980,)
Treino     : (1386, 60, 21)
Validação  : (297, 60, 21)
Teste      : (297, 60, 21)

  0%|          | 0/20 [00:00<?, ?it/s]

g:\Meu Drive\5. Cursos\Pós ML Engineering\Fase 4 - Deep Learning e IA\lstm-stock-predictor-api\.venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

[I 2026-07-07 07:06:23,250] Trial 0 finished with value: 0.027280865237116814 and parameters: {'units_1': 64, 'units_2': 48, 'dropout': 0.14545538427105129, 'learning_rate': 0.0020704203495016675, 'batch_size': 64}. Best is trial 0 with value: 0.027280865237116814.
[I 2026-07-07 07:06:59,878] Trial 1 finished with value: 0.026996400207281113 and parameters: {'units_1': 32, 'units_2': 32, 'dropout': 0.25179175785805674, 'learning_rate': 0.0019192393913613252, 'batch_size': 32}. Best is trial 1 with value: 0.026996400207281113.
[I 2026-07-07 07:07:58,822] Trial 2 finished with value: 0.034790992736816406 and parameters: {'units_1': 32, 'units_2': 16, 'dropout': 0.3002621132155989, 'learning_rate': 0.00014805778551175267, 'batch_size': 64}. Best is trial 1 with value: 0.026996400207281113.
[I 2026-07-07 07:08:12,403] Trial 3 finished with value: 0.025059109553694725 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.2136487444962062, 'learning_rate': 0.007185847332193528, 'batch_size': 64}. Best is trial 3 with value: 0.025059109553694725.
[I 2026-07-07 07:08:38,550] Trial 4 finished with value: 0.02575329691171646 and parameters: {'units_1': 32, 'units_2': 32, 'dropout': 0.3871925801588644, 'learning_rate': 0.005970231867294167, 'batch_size': 32}. Best is trial 3 with value: 0.025059109553694725.
[I 2026-07-07 07:09:16,262] Trial 5 finished with value: 0.027301566675305367 and parameters: {'units_1': 128, 'units_2': 16, 'dropout': 0.23330088309488517, 'learning_rate': 0.0024688047419852786, 'batch_size': 64}. Best is trial 3 with value: 0.025059109553694725.
[I 2026-07-07 07:11:09,564] Trial 6 finished with value: 0.027526430785655975 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.3473098736767001, 'learning_rate': 0.0001980604318637196, 'batch_size': 32}. Best is trial 3 with value: 0.025059109553694725.
[I 2026-07-07 07:11:47,442] Trial 7 finished with value: 0.02738070860505104 and parameters: {'units_1': 32, 'units_2': 48, 'dropout': 0.3091442891091515, 'learning_rate': 0.0009695076033442724, 'batch_size': 32}. Best is trial 3 with value: 0.025059109553694725.
[I 2026-07-07 07:13:24,713] Trial 8 finished with value: 0.027600515633821487 and parameters: {'units_1': 64, 'units_2': 64, 'dropout': 0.479113602705044, 'learning_rate': 0.0002686210952600963, 'batch_size': 32}. Best is trial 3 with value: 0.025059109553694725.
[I 2026-07-07 07:15:03,651] Trial 9 finished with value: 0.0275675430893898 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.2556148937979811, 'learning_rate': 0.00039176582598782217, 'batch_size': 64}. Best is trial 3 with value: 0.025059109553694725.
[I 2026-07-07 07:16:01,277] Trial 10 finished with value: 0.0255680400878191 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.1557413907553212, 'learning_rate': 0.005039875245635724, 'batch_size': 16}. Best is trial 3 with value: 0.025059109553694725.
[I 2026-07-07 07:16:54,526] Trial 11 finished with value: 0.0221028383821249 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.10257792703091059, 'learning_rate': 0.007972026115016611, 'batch_size': 16}. Best is trial 11 with value: 0.0221028383821249.
[I 2026-07-07 07:18:06,161] Trial 12 finished with value: 0.01999841257929802 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.10115401192611398, 'learning_rate': 0.009852485243069076, 'batch_size': 16}. Best is trial 12 with value: 0.01999841257929802.
[I 2026-07-07 07:18:46,772] Trial 13 finished with value: 0.022917727008461952 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.10019299123242176, 'learning_rate': 0.009785562239659448, 'batch_size': 16}. Best is trial 12 with value: 0.01999841257929802.
[I 2026-07-07 07:19:40,282] Trial 14 finished with value: 0.024922963231801987 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.10127499007325676, 'learning_rate': 0.0039860795937583, 'batch_size': 16}. Best is trial 12 with value: 0.01999841257929802.
[I 2026-07-07 07:20:13,094] Trial 15 finished with value: 0.024539252743124962 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.17638041620489645, 'learning_rate': 0.009994024665388556, 'batch_size': 16}. Best is trial 12 with value: 0.01999841257929802.
[I 2026-07-07 07:21:34,750] Trial 16 finished with value: 0.025401636958122253 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.1365321479374237, 'learning_rate': 0.003256009944399305, 'batch_size': 16}. Best is trial 12 with value: 0.01999841257929802.
[I 2026-07-07 07:22:29,944] Trial 17 finished with value: 0.02674555964767933 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.18485269776801036, 'learning_rate': 0.001246731807800287, 'batch_size': 16}. Best is trial 12 with value: 0.01999841257929802.
[I 2026-07-07 07:23:10,322] Trial 18 finished with value: 0.026499148458242416 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.10626273986855274, 'learning_rate': 0.005867370416245061, 'batch_size': 16}. Best is trial 12 with value: 0.01999841257929802.

[I 2026-07-07 07:24:59,761] A new study created in memory with name: LSTM Stock Prediction | window_size = 90

[I 2026-07-07 07:24:59,741] Trial 19 finished with value: 0.026806501671671867 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.19728334816137122, 'learning_rate': 0.0007619002655058835, 'batch_size': 16}. Best is trial 12 with value: 0.01999841257929802.
============================================================
Melhores hiperparâmetros | Ticker = VBBR3 | window_size = 60
============================================================
units_1: 96
units_2: 48
dropout: 0.10115401192611398
learning_rate: 0.009852485243069076
batch_size: 16

Melhor validation loss:
0.01999841257929802



============================================================
Início dos estudos | Ticker = VBBR3 | window_size = 90
============================================================
(1950, 90, 21)
(1950,)
Treino     : (1365, 90, 21)
Validação  : (292, 90, 21)
Teste      : (293, 90, 21)

  0%|          | 0/20 [00:00<?, ?it/s]

g:\Meu Drive\5. Cursos\Pós ML Engineering\Fase 4 - Deep Learning e IA\lstm-stock-predictor-api\.venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

[I 2026-07-07 07:27:10,924] Trial 0 finished with value: 0.026108918711543083 and parameters: {'units_1': 128, 'units_2': 16, 'dropout': 0.2093865325350769, 'learning_rate': 0.00038455304067538633, 'batch_size': 32}. Best is trial 0 with value: 0.026108918711543083.
[I 2026-07-07 07:28:35,334] Trial 1 finished with value: 0.025990664958953857 and parameters: {'units_1': 64, 'units_2': 16, 'dropout': 0.12848838744882862, 'learning_rate': 0.000751688377912916, 'batch_size': 16}. Best is trial 1 with value: 0.025990664958953857.
[I 2026-07-07 07:29:26,527] Trial 2 finished with value: 0.022081851959228516 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.3848725860876807, 'learning_rate': 0.009717512914278227, 'batch_size': 16}. Best is trial 2 with value: 0.022081851959228516.
[I 2026-07-07 07:30:18,529] Trial 3 finished with value: 0.02606603130698204 and parameters: {'units_1': 128, 'units_2': 16, 'dropout': 0.2969924742423381, 'learning_rate': 0.0011271477850424067, 'batch_size': 32}. Best is trial 2 with value: 0.022081851959228516.
[I 2026-07-07 07:31:50,255] Trial 4 finished with value: 0.024784857407212257 and parameters: {'units_1': 64, 'units_2': 64, 'dropout': 0.3202373247634429, 'learning_rate': 0.003398221579841946, 'batch_size': 32}. Best is trial 2 with value: 0.022081851959228516.
[I 2026-07-07 07:35:06,721] Trial 5 finished with value: 0.047906965017318726 and parameters: {'units_1': 128, 'units_2': 32, 'dropout': 0.4586052350215435, 'learning_rate': 0.00010086808899446979, 'batch_size': 64}. Best is trial 2 with value: 0.022081851959228516.
[I 2026-07-07 07:38:30,304] Trial 6 finished with value: 0.02626599185168743 and parameters: {'units_1': 64, 'units_2': 64, 'dropout': 0.2326207735612048, 'learning_rate': 0.0001319150988885211, 'batch_size': 32}. Best is trial 2 with value: 0.022081851959228516.
[I 2026-07-07 07:41:13,336] Trial 7 finished with value: 0.02610432356595993 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.15101132613824617, 'learning_rate': 0.00020235727819164015, 'batch_size': 16}. Best is trial 2 with value: 0.022081851959228516.
[I 2026-07-07 07:42:11,375] Trial 8 finished with value: 0.02557837963104248 and parameters: {'units_1': 96, 'units_2': 64, 'dropout': 0.46394610262915437, 'learning_rate': 0.0035725422094404235, 'batch_size': 64}. Best is trial 2 with value: 0.022081851959228516.
[I 2026-07-07 07:44:03,578] Trial 9 finished with value: 0.026037611067295074 and parameters: {'units_1': 96, 'units_2': 64, 'dropout': 0.21208669044622225, 'learning_rate': 0.0010011029075536603, 'batch_size': 64}. Best is trial 2 with value: 0.022081851959228516.
[I 2026-07-07 07:44:58,104] Trial 10 finished with value: 0.022630685940384865 and parameters: {'units_1': 32, 'units_2': 32, 'dropout': 0.3831654072247677, 'learning_rate': 0.009207193698254115, 'batch_size': 16}. Best is trial 2 with value: 0.022081851959228516.
[I 2026-07-07 07:45:36,633] Trial 11 finished with value: 0.022049449384212494 and parameters: {'units_1': 32, 'units_2': 32, 'dropout': 0.3820255871880517, 'learning_rate': 0.009759101352379774, 'batch_size': 16}. Best is trial 11 with value: 0.022049449384212494.
[I 2026-07-07 07:46:26,193] Trial 12 finished with value: 0.022465340793132782 and parameters: {'units_1': 32, 'units_2': 32, 'dropout': 0.38738582776637864, 'learning_rate': 0.009415427588420193, 'batch_size': 16}. Best is trial 11 with value: 0.022049449384212494.
[I 2026-07-07 07:48:23,461] Trial 13 finished with value: 0.022811971604824066 and parameters: {'units_1': 64, 'units_2': 48, 'dropout': 0.38290058055882886, 'learning_rate': 0.00391408441550366, 'batch_size': 16}. Best is trial 11 with value: 0.022049449384212494.
[I 2026-07-07 07:49:22,304] Trial 14 finished with value: 0.022763961926102638 and parameters: {'units_1': 32, 'units_2': 48, 'dropout': 0.49779654255870187, 'learning_rate': 0.005856888255843246, 'batch_size': 16}. Best is trial 11 with value: 0.022049449384212494.
[I 2026-07-07 07:51:00,595] Trial 15 finished with value: 0.02545783296227455 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.32459717475786876, 'learning_rate': 0.0019997068263169692, 'batch_size': 16}. Best is trial 11 with value: 0.022049449384212494.
[I 2026-07-07 07:51:52,618] Trial 16 finished with value: 0.023784080520272255 and parameters: {'units_1': 64, 'units_2': 48, 'dropout': 0.4310019830441054, 'learning_rate': 0.0069082322484716385, 'batch_size': 16}. Best is trial 11 with value: 0.022049449384212494.
[I 2026-07-07 07:53:01,493] Trial 17 finished with value: 0.025059271603822708 and parameters: {'units_1': 32, 'units_2': 32, 'dropout': 0.2730460846767297, 'learning_rate': 0.0022644326379558407, 'batch_size': 16}. Best is trial 11 with value: 0.022049449384212494.
[I 2026-07-07 07:54:11,937] Trial 18 finished with value: 0.023256421089172363 and parameters: {'units_1': 64, 'units_2': 48, 'dropout': 0.35199303673934773, 'learning_rate': 0.00431154318825622, 'batch_size': 16}. Best is trial 11 with value: 0.022049449384212494.

[I 2026-07-07 07:54:29,833] A new study created in memory with name: LSTM Stock Prediction | window_size = 120

[I 2026-07-07 07:54:29,801] Trial 19 finished with value: 0.024605177342891693 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.4206851385812823, 'learning_rate': 0.0062404489184067265, 'batch_size': 64}. Best is trial 11 with value: 0.022049449384212494.
============================================================
Melhores hiperparâmetros | Ticker = VBBR3 | window_size = 90
============================================================
units_1: 32
units_2: 32
dropout: 0.3820255871880517
learning_rate: 0.009759101352379774
batch_size: 16

Melhor validation loss:
0.022049449384212494



============================================================
Início dos estudos | Ticker = VBBR3 | window_size = 120
============================================================
(1920, 120, 21)
(1920,)
Treino     : (1344, 120, 21)
Validação  : (288, 120, 21)
Teste      : (288, 120, 21)

  0%|          | 0/20 [00:00<?, ?it/s]

g:\Meu Drive\5. Cursos\Pós ML Engineering\Fase 4 - Deep Learning e IA\lstm-stock-predictor-api\.venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

[I 2026-07-07 07:56:36,132] Trial 0 finished with value: 0.024591751396656036 and parameters: {'units_1': 128, 'units_2': 16, 'dropout': 0.18679541218150383, 'learning_rate': 0.0004684775467324754, 'batch_size': 32}. Best is trial 0 with value: 0.024591751396656036.
[I 2026-07-07 07:58:21,952] Trial 1 finished with value: 0.024349328130483627 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.34021898524436855, 'learning_rate': 0.0014808206181723782, 'batch_size': 32}. Best is trial 1 with value: 0.024349328130483627.
[I 2026-07-07 08:00:15,454] Trial 2 finished with value: 0.024397138506174088 and parameters: {'units_1': 128, 'units_2': 32, 'dropout': 0.2144606362010901, 'learning_rate': 0.0007352299056057314, 'batch_size': 16}. Best is trial 1 with value: 0.024349328130483627.
[I 2026-07-07 08:05:02,600] Trial 3 finished with value: 0.025305185467004776 and parameters: {'units_1': 128, 'units_2': 48, 'dropout': 0.4258249017006558, 'learning_rate': 0.000110655056626019, 'batch_size': 32}. Best is trial 1 with value: 0.024349328130483627.
[I 2026-07-07 08:05:54,160] Trial 4 finished with value: 0.024564653635025024 and parameters: {'units_1': 32, 'units_2': 32, 'dropout': 0.27806596611151924, 'learning_rate': 0.001326582600935265, 'batch_size': 64}. Best is trial 1 with value: 0.024349328130483627.
[I 2026-07-07 08:06:25,276] Trial 5 finished with value: 0.024386724457144737 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.4289590380119833, 'learning_rate': 0.0026115695452780634, 'batch_size': 32}. Best is trial 1 with value: 0.024349328130483627.
[I 2026-07-07 08:07:35,664] Trial 6 finished with value: 0.024355802685022354 and parameters: {'units_1': 96, 'units_2': 48, 'dropout': 0.4575554654359759, 'learning_rate': 0.0020907701593887514, 'batch_size': 64}. Best is trial 1 with value: 0.024349328130483627.
[I 2026-07-07 08:10:43,040] Trial 7 finished with value: 0.024681994691491127 and parameters: {'units_1': 64, 'units_2': 48, 'dropout': 0.3753773870120586, 'learning_rate': 0.00014357786111788708, 'batch_size': 32}. Best is trial 1 with value: 0.024349328130483627.
[I 2026-07-07 08:11:40,819] Trial 8 finished with value: 0.024466052651405334 and parameters: {'units_1': 32, 'units_2': 64, 'dropout': 0.19557979525558442, 'learning_rate': 0.0010184250351188038, 'batch_size': 32}. Best is trial 1 with value: 0.024349328130483627.
[I 2026-07-07 08:14:08,746] Trial 9 finished with value: 0.019745392724871635 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.4039246030810061, 'learning_rate': 0.007080448271048392, 'batch_size': 16}. Best is trial 9 with value: 0.019745392724871635.
[I 2026-07-07 08:15:03,956] Trial 10 finished with value: 0.022234775125980377 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.11817141450767246, 'learning_rate': 0.009693482686285384, 'batch_size': 16}. Best is trial 9 with value: 0.019745392724871635.
[I 2026-07-07 08:15:52,884] Trial 11 finished with value: 0.021391693502664566 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.12002825818514488, 'learning_rate': 0.009727264862729679, 'batch_size': 16}. Best is trial 9 with value: 0.019745392724871635.
[I 2026-07-07 08:17:09,807] Trial 12 finished with value: 0.020548928529024124 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.10122518396244284, 'learning_rate': 0.009743284879939907, 'batch_size': 16}. Best is trial 9 with value: 0.019745392724871635.
[I 2026-07-07 08:19:10,577] Trial 13 finished with value: 0.02095850557088852 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.27541078204508707, 'learning_rate': 0.004548690994843896, 'batch_size': 16}. Best is trial 9 with value: 0.019745392724871635.
[I 2026-07-07 08:20:09,176] Trial 14 finished with value: 0.022222191095352173 and parameters: {'units_1': 64, 'units_2': 48, 'dropout': 0.3359909989748029, 'learning_rate': 0.004722145150217382, 'batch_size': 16}. Best is trial 9 with value: 0.019745392724871635.
[I 2026-07-07 08:20:52,345] Trial 15 finished with value: 0.023495178669691086 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.4955398516225574, 'learning_rate': 0.005513935418712777, 'batch_size': 16}. Best is trial 9 with value: 0.019745392724871635.
[I 2026-07-07 08:21:36,823] Trial 16 finished with value: 0.02248391881585121 and parameters: {'units_1': 96, 'units_2': 64, 'dropout': 0.2641394403975119, 'learning_rate': 0.006209412196022402, 'batch_size': 16}. Best is trial 9 with value: 0.019745392724871635.
[I 2026-07-07 08:23:01,395] Trial 17 finished with value: 0.023157421499490738 and parameters: {'units_1': 128, 'units_2': 48, 'dropout': 0.1613135873488331, 'learning_rate': 0.002866501828541838, 'batch_size': 16}. Best is trial 9 with value: 0.019745392724871635.
[I 2026-07-07 08:23:24,709] Trial 18 finished with value: 0.02213001251220703 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.23754345875372884, 'learning_rate': 0.007582002617652604, 'batch_size': 64}. Best is trial 9 with value: 0.019745392724871635.

[I 2026-07-07 08:24:37,885] A new study created in memory with name: LSTM Stock Prediction | window_size = 180

[I 2026-07-07 08:24:37,873] Trial 19 finished with value: 0.021157091483473778 and parameters: {'units_1': 64, 'units_2': 16, 'dropout': 0.32429120239138653, 'learning_rate': 0.0035873493441501447, 'batch_size': 16}. Best is trial 9 with value: 0.019745392724871635.
============================================================
Melhores hiperparâmetros | Ticker = VBBR3 | window_size = 120
============================================================
units_1: 128
units_2: 64
dropout: 0.4039246030810061
learning_rate: 0.007080448271048392
batch_size: 16

Melhor validation loss:
0.019745392724871635



============================================================
Início dos estudos | Ticker = VBBR3 | window_size = 180
============================================================
(1860, 180, 21)
(1860,)
Treino     : (1302, 180, 21)
Validação  : (279, 180, 21)
Teste      : (279, 180, 21)

  0%|          | 0/20 [00:00<?, ?it/s]

g:\Meu Drive\5. Cursos\Pós ML Engineering\Fase 4 - Deep Learning e IA\lstm-stock-predictor-api\.venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

[I 2026-07-07 08:27:07,664] Trial 0 finished with value: 0.02073306404054165 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.461042151196278, 'learning_rate': 0.0014261522402190159, 'batch_size': 32}. Best is trial 0 with value: 0.02073306404054165.
[I 2026-07-07 08:30:02,125] Trial 1 finished with value: 0.020955529063940048 and parameters: {'units_1': 32, 'units_2': 32, 'dropout': 0.23976184091974592, 'learning_rate': 0.00044089234169939005, 'batch_size': 64}. Best is trial 0 with value: 0.02073306404054165.
[I 2026-07-07 08:30:53,093] Trial 2 finished with value: 0.019462214782834053 and parameters: {'units_1': 32, 'units_2': 16, 'dropout': 0.45406684415886134, 'learning_rate': 0.008244818771042361, 'batch_size': 32}. Best is trial 2 with value: 0.019462214782834053.
[I 2026-07-07 08:32:26,523] Trial 3 finished with value: 0.019859006628394127 and parameters: {'units_1': 32, 'units_2': 48, 'dropout': 0.409685374635242, 'learning_rate': 0.005021490464335611, 'batch_size': 32}. Best is trial 2 with value: 0.019462214782834053.
[I 2026-07-07 08:32:56,969] Trial 4 finished with value: 0.01704353280365467 and parameters: {'units_1': 96, 'units_2': 32, 'dropout': 0.441219257366559, 'learning_rate': 0.009398644684006594, 'batch_size': 64}. Best is trial 4 with value: 0.01704353280365467.
[I 2026-07-07 08:33:43,896] Trial 5 finished with value: 0.018516261130571365 and parameters: {'units_1': 32, 'units_2': 32, 'dropout': 0.3326536578444362, 'learning_rate': 0.006548889677704477, 'batch_size': 16}. Best is trial 4 with value: 0.01704353280365467.
[I 2026-07-07 08:39:33,294] Trial 6 finished with value: 0.020918378606438637 and parameters: {'units_1': 32, 'units_2': 32, 'dropout': 0.3615911016633875, 'learning_rate': 0.00013218682528449836, 'batch_size': 16}. Best is trial 4 with value: 0.01704353280365467.
[I 2026-07-07 08:40:05,531] Trial 7 finished with value: 0.02015078440308571 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.26439522416115896, 'learning_rate': 0.005924991666494498, 'batch_size': 64}. Best is trial 4 with value: 0.01704353280365467.
[I 2026-07-07 08:42:47,429] Trial 8 finished with value: 0.020952651277184486 and parameters: {'units_1': 64, 'units_2': 32, 'dropout': 0.12799077386226962, 'learning_rate': 0.0004613912158188229, 'batch_size': 32}. Best is trial 4 with value: 0.01704353280365467.
[I 2026-07-07 08:44:38,052] Trial 9 finished with value: 0.0195130817592144 and parameters: {'units_1': 128, 'units_2': 48, 'dropout': 0.1637127301298135, 'learning_rate': 0.004369573498423533, 'batch_size': 32}. Best is trial 4 with value: 0.01704353280365467.
[I 2026-07-07 08:47:26,924] Trial 10 finished with value: 0.020703529939055443 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.49892823598934216, 'learning_rate': 0.001495963167566826, 'batch_size': 64}. Best is trial 4 with value: 0.01704353280365467.
[I 2026-07-07 08:49:12,726] Trial 11 finished with value: 0.018001480028033257 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.33820573276109567, 'learning_rate': 0.009842960103383699, 'batch_size': 16}. Best is trial 4 with value: 0.01704353280365467.
[I 2026-07-07 08:51:25,930] Trial 12 finished with value: 0.019854841753840446 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.34198532999968656, 'learning_rate': 0.0026338532715527423, 'batch_size': 16}. Best is trial 4 with value: 0.01704353280365467.
[I 2026-07-07 08:54:04,773] Trial 13 finished with value: 0.017937038093805313 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.28035959588387327, 'learning_rate': 0.009967761089820077, 'batch_size': 16}. Best is trial 4 with value: 0.01704353280365467.
[I 2026-07-07 08:56:28,405] Trial 14 finished with value: 0.02052285708487034 and parameters: {'units_1': 96, 'units_2': 16, 'dropout': 0.23897635148176025, 'learning_rate': 0.00283456761263769, 'batch_size': 64}. Best is trial 4 with value: 0.01704353280365467.
[I 2026-07-07 08:58:57,606] Trial 15 finished with value: 0.018985163420438766 and parameters: {'units_1': 64, 'units_2': 48, 'dropout': 0.27705670944087407, 'learning_rate': 0.0029735756083274075, 'batch_size': 16}. Best is trial 4 with value: 0.01704353280365467.
[I 2026-07-07 08:59:35,581] Trial 16 finished with value: 0.016668247058987617 and parameters: {'units_1': 128, 'units_2': 16, 'dropout': 0.19182738644069613, 'learning_rate': 0.009797674366892857, 'batch_size': 64}. Best is trial 16 with value: 0.016668247058987617.
[I 2026-07-07 09:01:52,764] Trial 17 finished with value: 0.020799968391656876 and parameters: {'units_1': 128, 'units_2': 64, 'dropout': 0.1851168106460474, 'learning_rate': 0.001707001921178833, 'batch_size': 64}. Best is trial 16 with value: 0.016668247058987617.
[I 2026-07-07 09:03:33,256] Trial 18 finished with value: 0.020641759037971497 and parameters: {'units_1': 128, 'units_2': 48, 'dropout': 0.10339745489230351, 'learning_rate': 0.004123495779180349, 'batch_size': 64}. Best is trial 16 with value: 0.016668247058987617.
[I 2026-07-07 09:06:39,729] Trial 19 finished with value: 0.020883869379758835 and parameters: {'units_1': 128, 'units_2': 16, 'dropout': 0.3948948096131208, 'learning_rate': 0.0008520984636517647, 'batch_size': 64}. Best is trial 16 with value: 0.016668247058987617.
============================================================
Melhores hiperparâmetros | Ticker = VBBR3 | window_size = 180
============================================================
units_1: 128
units_2: 16
dropout: 0.19182738644069613
learning_rate: 0.009797674366892857
batch_size: 64

Melhor validation loss:
0.016668247058987617

## Avaliação e Definição

In [ ]:
def listar_arquivos_pasta(folder_path: str):

    files = []
    for (dirpath, dirnames, filenames) in walk(folder_path):
        files.extend(filenames)
        break

    return files

In [8]:
tb_abev = pd.DataFrame(
    data = {
        'ticker':'ABEV3',
        'window_size':[30, 60, 90, 120, 360],
        'val_loss':[0.00621827645227313, 0.005724024027585983, 0.005373380612581968, 0.004879966843873262, 0.00518820621073246], 
        'units_1':[64, 32, 128, 32, 32], 
        'units_2':[32, 16, 32, 16, 32], 
        'dropout':[0.29893700532625567, 0.21778495227726768, 0.3425725487095859, 0.3076547889480078, 0.4990013534433384],
        'learning_rate':[0.00015723169829245267, 0.0003489814349324155, 0.00020847351706535064, 0.0005856545376679272, 0.00035577683100581134], 
        'batch_size':[32, 64, 64, 64, 64] 
    }
)

In [9]:
tabela_hiperparams = pd.DataFrame()

for i in [i for i in listar_arquivos_pasta('dados/aux_data/') if i.endswith('.xlsx')]:
    tmp = pd.read_excel(f"dados/aux_data/{i}")
    tabela_hiperparams = pd.concat([tabela_hiperparams, tmp])

tabela_hiperparams = pd.concat([tabela_hiperparams, tb_abev])

tabela_hiperparams

,ticker,window_size,val_loss,units_1,units_2,dropout,learning_rate,batch_size
0,RENT3,60,0.06,96,16,0.10,0.01,32
1,RENT3,90,0.05,96,48,0.41,0.00,64
2,RENT3,120,0.03,96,48,0.20,0.01,16
3,RENT3,180,0.03,32,32,0.21,0.01,16
4,LREN3,60,0.00,64,16,0.50,0.00,16
5,LREN3,90,0.00,32,48,0.25,0.00,32
6,LREN3,120,0.00,32,32,0.17,0.00,64
7,LREN3,180,0.00,32,48,0.44,0.00,64
0,SMFT3,60,0.04,96,32,0.13,0.01,32
1,SMFT3,90,0.04,96,48,0.12,0.01,16
2,SMFT3,120,0.04,32,64,0.24,0.01,16
3,SMFT3,180,0.05,96,16,0.24,0.01,16
0,VBBR3,60,0.02,96,48,0.10,0.01,16
1,VBBR3,90,0.02,32,32,0.38,0.01,16
2,VBBR3,120,0.02,128,64,0.40,0.01,16
3,VBBR3,180,0.02,128,16,0.19,0.01,64
0,MULT3,60,0.03,128,48,0.36,0.01,16
1,MULT3,90,0.03,64,32,0.23,0.01,16
2,MULT3,120,0.03,64,64,0.31,0.01,16
3,MULT3,180,0.03,32,48,0.16,0.01,32
0,ABEV3,30,0.01,64,32,0.30,0.00,32
1,ABEV3,60,0.01,32,16,0.22,0.00,64
2,ABEV3,90,0.01,128,32,0.34,0.00,64
3,ABEV3,120,0.00,32,16,0.31,0.00,64
4,ABEV3,360,0.01,32,32,0.50,0.00,64

In [15]:
with pd.option_context('display.float_format', '{:,.5f}'.format):
    display(tabela_hiperparams.sort_values('val_loss').drop_duplicates(subset = 'ticker'))

,ticker,window_size,val_loss,units_1,units_2,dropout,learning_rate,batch_size
7,LREN3,180,0.00269,32,48,0.43652,0.00021,64
3,ABEV3,120,0.00488,32,16,0.30765,0.00059,64
3,VBBR3,180,0.01667,128,16,0.19183,0.00980,64
2,MULT3,120,0.02832,64,64,0.30618,0.00895,16
3,RENT3,180,0.03029,32,32,0.20686,0.00625,16
0,SMFT3,60,0.03602,96,32,0.12643,0.00920,32

In [17]:
tabela_hiperparams.sort_values('val_loss').drop_duplicates(subset = 'ticker').to_excel('dados/refined/tabela_melhores_hiperparametros.xlsx', index = False)

## 2º teste de hiperparametros

In [ ]:
for t in tickers:

    tabela_hiperparams = pd.DataFrame()

    df = pd.read_parquet(f"{save_folder_path_refined}/tb_analitica_{t}.parquet", engine = 'pyarrow')
    df = df[df['close'].notna()]
    df = df.sort_values("date").reset_index(drop=True)

    data = df[features].copy()

    # ==============================================================================
    # Split temporal do DataFrame
    # ==============================================================================

    n = len(data)

    train_end = int(n * 0.70)
    valid_end = int(n * 0.85)

    train_df = data.iloc[:train_end].copy()
    valid_df = data.iloc[train_end:valid_end].copy()
    test_df  = data.iloc[valid_end:].copy()

    # ==============================================================================
    # Normalização
    # O scaler é ajustado SOMENTE nos dados de treino
    # ==============================================================================

    scaler = RobustScaler()

    scaler.fit(train_df)

    train_scaled = scaler.transform(train_df)
    valid_scaled = scaler.transform(valid_df)
    test_scaled  = scaler.transform(test_df)

    # ==============================================================================
    # Construção das sequências
    # Cada conjunto gera suas próprias sequências
    # ==============================================================================

    print("=" * 60)
    print(f"Início dos estudos | Ticker = {t}")
    print("=" * 60)

    study = get_study_optuna(train_scaled, valid_scaled, test_scaled, n_trials = 50, ticker = t)

    tmp = pd.DataFrame(data = {
        'ticker':[t],
        'val_loss_mse':[study.best_value]
    })

    for k, v in study.best_params.items():
        tmp[k] = [v]

    tabela_hiperparams = pd.concat([tabela_hiperparams, tmp])
    print("\n\n")

    tabela_hiperparams.to_excel(f'dados/aux_data/tabela_hiperparametros_{t}.xlsx', index = False)